project_id = "zsvbolcyxsrzriqausiu"

[auth]
[auth.email]
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
redirect_uri = "http://localhost:3000/auth"

[auth.external.apple]
enabled = true
client_id = "env(SUPABASE_AUTH_APPLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_APPLE_SECRET)"
redirect_uri = "http://localhost:3000/auth"
